<?php
$todoList = $this->getData('todolist');
?>

<?php include(BASE_DIR . '/templates/head.phtml') ?>

    To Do List

        <?php foreach ($todoList as $todo) : ?>
            <?php $bgColor = $todo['completed'] == 'true' ? '#2ecc71' : '#e74c3c' ?>
                <p>Utilisateur n° : <?= $todo['userId'] ?></p>
                <p>N° de la tâche : <?= $todo['id'] ?></p>
                <p>Nom de la tâche : <?= $todo['title'] ?></p>
                <p>Statut : <?= $todo['completed'] == 'true' ? 'Faite' : 'Pas encore faite' ?></p>
        <?php endforeach; ?>

<?php include(BASE_DIR . '/templates/footer.phtml') ?>